### ISSUE TITLE
Sign in with GitHub does not work

### ISSUE THREAD

**Issue by lvaroqui** [Axosoft/glo-vs-code#12]
Sign In With Github button doesn't work, it does not open a web page. I am running i3 which may be the problem.

**Comment by gigi206** [comment]
I have the same issue. 

When I click on sign in with GitHub nothing happens... No web browser open.

I use Linux, **gtk-launch** works.

![](https://i.ibb.co/0qV515Q/Capture-d-cran-de-2020-05-04-13-52-52.png)

**Comment by gigi206** [comment]
@lvaroqui, do you use VSCodium ? It seems the issue is a VSCodium issue.

**Comment by STLnick** [comment]
I'm also unable to sign in to the Boards extension in VS Code using the GitHub button. Nothing happens and no popup appears. I authorized my GitHub account in my browser on the site for GK Boards but I'm still unable to login through the extension.

VS Code: Version: 1.47.0
macOS Catalina Version 10.15.5

**Comment by alec-joy** [comment]
Same for me though I think the issue may be that I am using the VScode remote extension, so GK Boards is technically installed inside of a container which doesn't have a window manager or browser. 

I don't know how to solve that particular problem but the easy workaround would be to allow users to add a password to github connected accounts so we can also just login the normal way.

**Comment by BStatic** [comment]
I had the same issue so I checked the console. It was returning 401 from the user or users endpoint and said invalid access token.

**Comment by stephenstack** [comment]
Same problem, reported it direct. but not response. Not huge confidence here unless dev updates progress to resolution. I deleted my Github auth from the main site, and setup a 'ordinary' user/pass. After sign in for the extension using these creds, none of the 'connect to github' buttons work for new or existing boards. They all attempt something, but no response or errors. So, extension not working as designed.

**Comment by stephenstack** [comment]
Small update, I have the remote-ssh extension installed also, but have tried with local and remote workspaces, still not working on both.

**Comment by stephenstack** [comment]
Identical to this, https://github.com/Axosoft/glo-vs-code/issues/6#issuecomment-496292099

https://marketplace.visualstudio.com/items?itemName=axosoft.gitkraken-glo v1.1.1

Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by maxpermal** [comment]
> 
> 
> Identical to this, [#6 (comment)](https://github.com/Axosoft/glo-vs-code/issues/6#issuecomment-496292099)
> 
> https://marketplace.visualstudio.com/items?itemName=axosoft.gitkraken-glo v1.1.1
> 
> Version: 1.47.2 (user setup)
> Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
> Date: 2020-07-15T18:22:06.216Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.17763

I ve got the same problem.
tips : I ve downgraded vscode to 1.46 and it works then at updating vscode to 1.47 i ve got the same probem

**Comment by maxpermal** [comment]
The problem solved for me after linking again gitkraken to github at the url "https://github.com/marketplace/gitkraken-glo-boards".
tips : before linking the extension again, it was written in the vscode debugger console "access token error"...
