### ISSUE TITLE
Drag & drop does not work.

### ISSUE THREAD

**Issue by niem94** [Axosoft/glo-vs-code#13]
I'm on MacBook Pro (16-inch, 2019) running macOS Catalina 10.15.4.

Drag & drop only allows me to drag cards around, but dropping them takes them right back to where they were dragged from.
This has been a problem since I first installed this extension, and it is quite a big annoyance, as I have to go into the card, and use the dropdown list to change what status/column it is in.

**Comment by tbaden** [comment]
same on MacBook Pro (15-inch, 2019) HighSierra 10.13.6.
in older versions I had this issue when a had a debugger running in vscode, which resolved itself, when the debugger stopped. 
Now the issue is permanent, maybe another extension interferes in this case.
