### ISSUE TITLE
Cannot open glo board

### ISSUE THREAD

**Issue by deckerbl** [Axosoft/glo-vs-code#15]
Just installed the extension into VS Code and when I open glo either from the bar at the bottom or using the command list the glo tab is just an empty page.  Doesn't ask me to login to Gitkraken or anything.   The tab is empty.

<img width="824" alt="EmptyGlo" src="https://user-images.githubusercontent.com/20360642/85205991-8f9dea00-b2e4-11ea-8aa1-11b5337f4855.PNG">

**Comment by maxnorris** [comment]
Getting this as well.  Fresh install of Win10 2004, Code 1.46.1.  Had it working in an old install just fine, and the stand-alone app version of GitKraken is working properly as well. I see it very quickly flash something on the panel then it goes blank like the image above.  Dev tools console produces this if it helps any.

`[Embedded Page] VSCode iframe detected
webviewElement.ts:331 [Embedded Page] Glo host: VSCode
webviewElement.ts:331 [Embedded Page] [bugsnag] Loaded!
webviewElement.ts:331 [Embedded Page] Glo mode: production
webviewElement.ts:331 [Embedded Page] Glo version: 1.20.1
webviewElement.ts:331 [Embedded Page] No accessToken
webviewElement.ts:331 [Embedded Page] Uncaught SecurityError: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.`

**Comment by Destaq** [comment]
Happens to me too on Mac @maxnorris , @deckerbl could you please link to the extension that you installed? Mine says `GK Boards` instead but I can't find any extension in the marketplace named 'Glo'.

**Comment by maxnorris** [comment]
> Happens to me too on Mac @maxnorris , @deckerbl could you please link to the extension that you installed? Mine says `GK Boards` instead but I can't find any extension in the marketplace named 'Glo'.

Listed as "GitKraken Boards":
`https://marketplace.visualstudio.com/items?itemName=axosoft.gitkraken-glo`

**Comment by deckerbl** [comment]
> Happens to me too on Mac @maxnorris , @deckerbl could you please link to the extension that you installed? Mine says `GK Boards` instead but I can't find any extension in the marketplace named 'Glo'.

Same as @maxnorris 
https://marketplace.visualstudio.com/items?itemName=axosoft.gitkraken-glo

**Comment by deckerbl** [comment]
@Destaq @maxnorris Looks like a new release was pushed that changed the name to GK Boards

**Comment by maxnorris** [comment]
Yep, seeing the 1.1.1 update, still fails to load though sadly. I mean I can use the app version side by side for now till it's sorted out, just ridiculously convenient to have it right in the IDE.

**Comment by maxnorris** [comment]
Looks like whatever the problem was has been fixed -- the extension presented me with the login page and everything seems to be working nicely again.

**Comment by deckerbl** [comment]
@maxnorris seems to be working for me now as well.
