### ISSUE TITLE
"Sign in with Github" is not working

### ISSUE THREAD

**Issue by frontendmonster** [Axosoft/glo-vs-code#6]
```
VSCode Version: 1.32.3 (OSS)
Arch: x64
OS: GNU/Linux Manjaro
```

This is what console says:
> [Embedded Page] Blocked opening '' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

**Comment by mycroft16** [comment]
I am having the same issue:
VSCode Version: 1.35.0-insider
OS: Windows_NT x64 10.0.17763 (running in WSL from Ubuntu)

Clicking sign in with GitHub has no visible result. No warnings, no errors.
So I created an account using my email online and then signed in with that, but clicking "Connect to GitHub" just blocks the button for a minute and puts up a spinner, then nothing happens.

From the web interface, everything works as expected, but I need to be able to access this from within VSCode to really enjoy the benefits.

**Comment by jdgarcia** [comment]
Finally figured out that this issue is specific to the Insiders edition. Bug will be fixed in the next Glo update, I'll update and close this issue when the fix is out.

**Comment by jdgarcia** [comment]
This issue has been fixed in the Glo update that went out yesterday. You might have to restart VS Code for the changes to take effect since Glo could be cached.

https://support.gitkraken.com/glo-release-notes/current/#update-5302019
