### ISSUE TITLE
Cannot login with Github

### ISSUE THREAD

**Issue by kaankoken** [Axosoft/glo-vs-code#9]
Issue Type: <b>Bug</b>

I installed the extension. Then I launched it. I tried to login but it does not work at all. I cannot click the button

Extension version: 1.1.0
VS Code version: Code - OSS 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-22T07:38:21.043Z)
OS version: Linux x64 4.19.62-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2450)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.54GB (0.91GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by thefoxie** [comment]
Same here.

**Comment by kaankoken** [comment]
> Same here.

I solved the problem changing to aur vusiual-studio-code
